import {
  Activity,
  AlertTriangle,
  BarChart3,
  CalendarDays,
  DollarSign,
  Eye,
  FileText,
  Globe,
  HeartPulse,
  Image,
  LineChart,
  Megaphone,
  MessageSquare,
  Newspaper,
  Package,
  Palette,
  PenLine,
  PenSquare,
  Plug,
  Search,
  Settings,
  ShoppingBag,
  Star,
  TrendingUp,
  Users,
  Wrench,
} from "lucide-react"
import { renderQuickDraft } from "@/widgets/QuickDraftForm"
import { renderSiteHealth } from "@/widgets/SiteHealthMeter"
import type { Recipe } from "@/widgets/types"

export const adminRecipe: Recipe = {
  id: "admin",
  role: "Solo store owner",
  widgets: [
    {
      id: "metric-revenue",
      kind: "analytics",
      title: "Revenue this week",
      icon: DollarSign,
      size: "xl",
      metric: {
        value: "$8,420",
        delta: { value: "+12.4%", trend: "up" },
        sparkline: [620, 740, 690, 880, 940, 1120, 1260],
        caption: "vs. last week",
      },
    },
    {
      id: "metric-orders",
      kind: "analytics",
      title: "Orders this week",
      icon: ShoppingBag,
      size: "xl",
      metric: {
        value: "184",
        delta: { value: "+8", trend: "up" },
        sparkline: [22, 19, 24, 27, 31, 28, 33],
        caption: "vs. last week",
      },
    },
    {
      id: "metric-conversion",
      kind: "analytics",
      title: "Conversion rate",
      icon: TrendingUp,
      size: "xl",
      metric: {
        value: "2.4%",
        delta: { value: "-0.2%", trend: "down" },
        sparkline: [2.7, 2.8, 2.6, 2.5, 2.4, 2.5, 2.4],
        caption: "vs. last week",
      },
    },
    {
      id: "info-recent-orders",
      kind: "info",
      title: "Recent orders",
      icon: ShoppingBag,
      size: "wide",
      items: [
        {
          id: "o1",
          title: "#1284 — Sarah Kowalski",
          meta: "$129.00 · 2m ago",
          thumbnail: { kind: "avatar", name: "Sarah Kowalski" },
        },
        {
          id: "o2",
          title: "#1283 — Marco Delgado",
          meta: "$48.00 · 38m ago",
          thumbnail: { kind: "avatar", name: "Marco Delgado" },
        },
        {
          id: "o3",
          title: "#1282 — Anya Petrova",
          meta: "$210.00 · 1h ago",
          thumbnail: { kind: "avatar", name: "Anya Petrova" },
        },
        {
          id: "o4",
          title: "#1281 — Lee Harper",
          meta: "$76.00 · 2h ago",
          thumbnail: { kind: "avatar", name: "Lee Harper" },
        },
        {
          id: "o5",
          title: "#1280 — Jess Maru",
          meta: "$94.00 · 3h ago",
          thumbnail: { kind: "avatar", name: "Jess Maru" },
        },
        {
          id: "o6",
          title: "#1279 — Tomás Reyes",
          meta: "$162.00 · 5h ago",
          thumbnail: { kind: "avatar", name: "Tomás Reyes" },
        },
        {
          id: "o7",
          title: "#1278 — Priya Nair",
          meta: "$58.00 · Yesterday",
          thumbnail: { kind: "avatar", name: "Priya Nair" },
        },
        {
          id: "o8",
          title: "#1277 — Connor Boyle",
          meta: "$245.00 · Yesterday",
          thumbnail: { kind: "avatar", name: "Connor Boyle" },
        },
        {
          id: "o9",
          title: "#1276 — Hannah Liang",
          meta: "$112.00 · 2d ago",
          thumbnail: { kind: "avatar", name: "Hannah Liang" },
        },
        {
          id: "o10",
          title: "#1275 — Felix Adeyemi",
          meta: "$36.00 · 2d ago",
          thumbnail: { kind: "avatar", name: "Felix Adeyemi" },
        },
      ],
    },
    {
      id: "info-low-stock",
      kind: "info",
      title: "Low stock",
      icon: AlertTriangle,
      size: "wide",
      items: [
        {
          id: "s1",
          title: "Linen tote — natural",
          meta: "3 left",
          thumbnail: { kind: "image", seed: "linen-tote-natural" },
        },
        {
          id: "s2",
          title: "Brass lamp — small",
          meta: "2 left",
          thumbnail: { kind: "image", seed: "brass-lamp-small" },
        },
        {
          id: "s3",
          title: "Ceramic mug — sage",
          meta: "5 left",
          thumbnail: { kind: "image", seed: "ceramic-mug-sage" },
        },
        {
          id: "s4",
          title: "Wool throw — charcoal",
          meta: "Out of stock",
          thumbnail: { kind: "image", seed: "wool-throw-charcoal" },
        },
        {
          id: "s5",
          title: "Cotton scarf — sand",
          meta: "4 left",
          thumbnail: { kind: "image", seed: "cotton-scarf-sand" },
        },
        {
          id: "s6",
          title: "Reed diffuser — fig",
          meta: "1 left",
          thumbnail: { kind: "image", seed: "reed-diffuser-fig" },
        },
        {
          id: "s7",
          title: "Beeswax candle — amber",
          meta: "6 left",
          thumbnail: { kind: "image", seed: "beeswax-candle-amber" },
        },
        {
          id: "s8",
          title: "Walnut tray — large",
          meta: "Out of stock",
          thumbnail: { kind: "image", seed: "walnut-tray-large" },
        },
      ],
    },
    {
      id: "info-reviews",
      kind: "info",
      title: "New reviews",
      icon: Star,
      size: "wide",
      items: [
        {
          id: "r1",
          title: "★★★★★ Linen tote",
          meta: "“Beautiful quality.” — Sarah K.",
          thumbnail: { kind: "image", seed: "linen-tote-natural" },
        },
        {
          id: "r2",
          title: "★★★★☆ Brass lamp",
          meta: "“Sturdier than I expected.” — Marco D.",
          thumbnail: { kind: "image", seed: "brass-lamp-small" },
        },
        {
          id: "r3",
          title: "★★★★★ Ceramic mug",
          meta: "“Bought four.” — Anya P.",
          thumbnail: { kind: "image", seed: "ceramic-mug-sage" },
        },
        {
          id: "r4",
          title: "★★★★☆ Wool throw",
          meta: "“Cosy and well made.” — Lee H.",
          thumbnail: { kind: "image", seed: "wool-throw-charcoal" },
        },
        {
          id: "r5",
          title: "★★★★★ Cotton scarf",
          meta: "“Soft and warm.” — Jess M.",
          thumbnail: { kind: "image", seed: "cotton-scarf-sand" },
        },
        {
          id: "r6",
          title: "★★★☆☆ Reed diffuser",
          meta: "“Pleasant but faint.” — Tomás R.",
          thumbnail: { kind: "image", seed: "reed-diffuser-fig" },
        },
        {
          id: "r7",
          title: "★★★★★ Beeswax candle",
          meta: "“Burns clean for hours.” — Priya N.",
          thumbnail: { kind: "image", seed: "beeswax-candle-amber" },
        },
        {
          id: "r8",
          title: "★★★★★ Walnut tray",
          meta: "“The grain is gorgeous.” — Connor B.",
          thumbnail: { kind: "image", seed: "walnut-tray-large" },
        },
      ],
    },
    {
      id: "info-activity",
      kind: "info",
      title: "Recent activity",
      icon: Activity,
      size: "wide",
      items: [
        {
          id: "a1",
          title: "Published “Spring collection”",
          meta: "12m ago",
          thumbnail: { kind: "icon", icon: PenSquare },
        },
        {
          id: "a2",
          title: "Refunded order #1278",
          meta: "1h ago",
          thumbnail: { kind: "icon", icon: ShoppingBag },
        },
        {
          id: "a3",
          title: "Plugin update: Yoast SEO 22.4",
          meta: "2h ago",
          thumbnail: { kind: "icon", icon: Plug },
        },
        {
          id: "a4",
          title: "Updated homepage hero",
          meta: "Yesterday",
          thumbnail: { kind: "icon", icon: Image },
        },
        {
          id: "a5",
          title: "Approved 3 new reviews",
          meta: "Yesterday",
          thumbnail: { kind: "icon", icon: Star },
        },
        {
          id: "a6",
          title: "Replied to comment on “Sourcing linen”",
          meta: "2d ago",
          thumbnail: { kind: "icon", icon: MessageSquare },
        },
        {
          id: "a7",
          title: "Restocked Brass lamp — small",
          meta: "2d ago",
          thumbnail: { kind: "icon", icon: Package },
        },
        {
          id: "a8",
          title: "Added Marketing campaign “Mother's Day”",
          meta: "3d ago",
          thumbnail: { kind: "icon", icon: Megaphone },
        },
        {
          id: "a9",
          title: "Updated theme to Twenty Twenty-Six",
          meta: "4d ago",
          thumbnail: { kind: "icon", icon: Palette },
        },
        {
          id: "a10",
          title: "Invited new user: priya@store.example",
          meta: "5d ago",
          thumbnail: { kind: "icon", icon: Users },
        },
      ],
    },
    {
      id: "info-quick-draft",
      kind: "info",
      title: "Quick draft",
      icon: PenLine,
      size: "lg",
      render: renderQuickDraft,
    },
    {
      id: "info-site-health",
      kind: "info",
      title: "Site Health",
      icon: HeartPulse,
      size: "lg",
      render: renderSiteHealth,
    },
    {
      id: "info-wp-events",
      kind: "info",
      title: "WordPress Events and News",
      icon: CalendarDays,
      size: "wide",
      items: [
        {
          id: "e1",
          title: "WordCamp Europe 2026 — Basel",
          meta: "Jun 4–6 · In person",
          thumbnail: { kind: "icon", icon: CalendarDays },
        },
        {
          id: "e2",
          title: "Bristol WordPress Meetup",
          meta: "Thu, May 7 · 18:30 BST",
          thumbnail: { kind: "icon", icon: CalendarDays },
        },
        {
          id: "e3",
          title: "WordPress Accessibility Day 2026",
          meta: "Oct 14–15 · Online",
          thumbnail: { kind: "icon", icon: CalendarDays },
        },
        {
          id: "e4",
          title: "WordPress 6.9 Release Candidate 1",
          meta: "WordPress.org News · 1d ago",
          thumbnail: { kind: "site", domain: "wordpress.org" },
        },
        {
          id: "e5",
          title: "People of WordPress: Maya Lin",
          meta: "WP Tavern · 3d ago",
          thumbnail: { kind: "site", domain: "wptavern.com" },
        },
        {
          id: "e6",
          title: "What's new in the Site Editor",
          meta: "Make WordPress Core · 4d ago",
          thumbnail: { kind: "site", domain: "make.wordpress.org" },
        },
        {
          id: "e7",
          title: "Block Themes hit 60% adoption",
          meta: "WP Tavern · 1w ago",
          thumbnail: { kind: "site", domain: "wptavern.com" },
        },
        {
          id: "e8",
          title: "Roadmap: Phase 3 Collaboration",
          meta: "WordPress.org News · 2w ago",
          thumbnail: { kind: "site", domain: "wordpress.org" },
        },
      ],
    },
    {
      id: "info-yoast-seo",
      kind: "info",
      title: "Yoast SEO Posts Overview",
      icon: Search,
      size: "wide",
      items: [
        { id: "y1", title: "Posts with a good SEO score", meta: "24" },
        { id: "y2", title: "Posts that need improvement", meta: "9" },
        { id: "y3", title: "Posts with problems", meta: "3" },
        { id: "y4", title: "Posts without a focus keyphrase", meta: "5" },
      ],
    },
    {
      id: "metric-jetpack-views",
      kind: "analytics",
      title: "Site views",
      icon: Eye,
      size: "xl",
      metric: {
        value: "12,840",
        delta: { value: "+18.2%", trend: "up" },
        sparkline: [820, 1040, 980, 1320, 1420, 1610, 1820],
        caption: "Last 7 days",
      },
    },
    {
      id: "metric-jetpack-visitors",
      kind: "analytics",
      title: "Visitors",
      icon: LineChart,
      size: "xl",
      metric: {
        value: "4,210",
        delta: { value: "+6.4%", trend: "up" },
        sparkline: [340, 380, 360, 410, 430, 460, 510],
        caption: "Last 7 days",
      },
    },
    {
      id: "info-jetpack-top-content",
      kind: "info",
      title: "Top posts & pages",
      icon: BarChart3,
      size: "wide",
      items: [
        {
          id: "t1",
          title: "Spring collection lookbook",
          meta: "1,284 views",
          thumbnail: { kind: "image", seed: "spring-collection-lookbook" },
        },
        {
          id: "t2",
          title: "Brass lamp — small",
          meta: "962 views",
          thumbnail: { kind: "image", seed: "brass-lamp-small" },
        },
        {
          id: "t3",
          title: "How we source linen",
          meta: "748 views",
          thumbnail: { kind: "image", seed: "how-we-source-linen" },
        },
        {
          id: "t4",
          title: "Homepage",
          meta: "612 views",
          thumbnail: { kind: "image", seed: "homepage-hero" },
        },
        {
          id: "t5",
          title: "Linen tote — natural",
          meta: "508 views",
          thumbnail: { kind: "image", seed: "linen-tote-natural" },
        },
        {
          id: "t6",
          title: "Care guide: linen and wool",
          meta: "421 views",
          thumbnail: { kind: "image", seed: "linen-wool-care" },
        },
        {
          id: "t7",
          title: "Why we switched to organic dyes",
          meta: "362 views",
          thumbnail: { kind: "image", seed: "organic-dyes" },
        },
        {
          id: "t8",
          title: "About the studio",
          meta: "298 views",
          thumbnail: { kind: "image", seed: "studio-spring" },
        },
        {
          id: "t9",
          title: "Ceramic mug — sage",
          meta: "246 views",
          thumbnail: { kind: "image", seed: "ceramic-mug-sage" },
        },
        {
          id: "t10",
          title: "Beeswax candle — amber",
          meta: "204 views",
          thumbnail: { kind: "image", seed: "beeswax-candle-amber" },
        },
      ],
    },
    {
      id: "info-jetpack-referrers",
      kind: "info",
      title: "Top referrers",
      icon: Newspaper,
      size: "lg",
      items: [
        {
          id: "ref1",
          title: "Search engines",
          meta: "2,140",
          thumbnail: { kind: "icon", icon: Search },
        },
        {
          id: "ref2",
          title: "instagram.com",
          meta: "684",
          thumbnail: { kind: "site", domain: "instagram.com" },
        },
        {
          id: "ref3",
          title: "wordpress.com reader",
          meta: "412",
          thumbnail: { kind: "site", domain: "wordpress.com" },
        },
        {
          id: "ref4",
          title: "Direct",
          meta: "388",
          thumbnail: { kind: "icon", icon: Globe },
        },
        {
          id: "ref5",
          title: "pinterest.com",
          meta: "264",
          thumbnail: { kind: "site", domain: "pinterest.com" },
        },
        {
          id: "ref6",
          title: "news.ycombinator.com",
          meta: "182",
          thumbnail: { kind: "site", domain: "news.ycombinator.com" },
        },
        {
          id: "ref7",
          title: "reddit.com",
          meta: "146",
          thumbnail: { kind: "site", domain: "reddit.com" },
        },
        {
          id: "ref8",
          title: "Email newsletter",
          meta: "118",
          thumbnail: { kind: "icon", icon: MessageSquare },
        },
      ],
    },
    {
      id: "nav-classic",
      kind: "nav",
      size: "tall",
      items: [
        // Dock — prominent commerce contexts the solo owner switches
        // into multiple times a day.
        {
          id: "n-pages",
          title: "Pages",
          icon: FileText,
          action: { type: "pages" },
        },
        {
          id: "n-products",
          title: "Products",
          icon: Package,
          action: {
            type: "edit-page",
            params: { id: "products" },
            title: "Products",
          },
        },
        {
          id: "n-orders",
          title: "Orders",
          icon: ShoppingBag,
          action: { type: "orders" },
          badge: "12",
        },
        {
          id: "n-product-reviews",
          title: "Product reviews",
          icon: Star,
          action: { type: "product-reviews" },
          badge: "8",
        },
        {
          id: "n-marketing",
          title: "Marketing",
          icon: Megaphone,
          action: { type: "marketing" },
        },
        {
          id: "n-analytics",
          title: "Analytics",
          icon: BarChart3,
          action: { type: "analytics" },
        },
        {
          id: "n-settings",
          title: "Settings",
          icon: Settings,
          action: { type: "settings" },
        },

        // Dashboard launch tiles — less-prominent admin destinations.
        // Reachable in one click but not worth permanent dock real estate.
        {
          id: "n-posts",
          title: "Posts",
          icon: PenSquare,
          action: { type: "edit-page", params: { id: "posts" }, title: "Posts" },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-media",
          title: "Media",
          icon: Image,
          action: { type: "edit-page", params: { id: "media" }, title: "Media" },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-comments",
          title: "Comments",
          icon: MessageSquare,
          action: { type: "edit-page", params: { id: "comments" }, title: "Comments" },
          badge: "3",
          defaultPlacement: "dashboard",
        },
        {
          id: "n-users",
          title: "Users",
          icon: Users,
          action: { type: "edit-page", params: { id: "users" }, title: "Users" },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-appearance",
          title: "Appearance",
          icon: Palette,
          action: { type: "editor", title: "Appearance" },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-plugins",
          title: "Plugins",
          icon: Plug,
          action: { type: "edit-page", params: { id: "plugins" }, title: "Plugins" },
          badge: "2",
          defaultPlacement: "dashboard",
        },
        {
          id: "n-tools",
          title: "Tools",
          icon: Wrench,
          action: { type: "edit-page", params: { id: "tools" }, title: "Tools" },
          defaultPlacement: "dashboard",
        },
      ],
    },
  ],
}
