import {
  Activity,
  BarChart3,
  FileEdit,
  FileText,
  Image,
  Megaphone,
  MessageSquare,
  Package,
  Palette,
  PenSquare,
  Plug,
  Settings,
  ShoppingBag,
  Star,
  TrendingUp,
  Users,
  Wrench,
} from "lucide-react"
import type { Recipe } from "@/widgets/types"

export const adminRecipe: Recipe = {
  id: "admin",
  role: "Administrator",
  greeting: "Everything across your site, in one place.",
  widgets: [
    {
      id: "metric-traffic",
      kind: "analytics",
      title: "Visitors this week",
      icon: TrendingUp,
      size: "lg",
      metric: {
        value: "12.4k",
        delta: { value: "+6.8%", trend: "up" },
        sparkline: [820, 940, 1020, 1180, 1340, 1410, 1620],
        caption: "vs. last week",
      },
    },
    {
      id: "metric-orders",
      kind: "analytics",
      title: "Orders this week",
      icon: ShoppingBag,
      size: "lg",
      metric: {
        value: "184",
        delta: { value: "+8", trend: "up" },
        sparkline: [22, 19, 24, 27, 31, 28, 33],
        caption: "vs. last week",
      },
    },
    {
      id: "metric-comments",
      kind: "analytics",
      title: "New comments",
      icon: MessageSquare,
      size: "lg",
      metric: {
        value: "47",
        delta: { value: "-3", trend: "down" },
        sparkline: [9, 11, 8, 7, 6, 8, 5],
        caption: "vs. last week",
      },
    },
    {
      id: "info-drafts",
      kind: "info",
      title: "Drafts in progress",
      icon: FileEdit,
      size: "xl",
      items: [
        { id: "d1", title: "Spring collection — preview", meta: "Edited 12m ago" },
        { id: "d2", title: "About the studio", meta: "Edited 2h ago" },
        { id: "d3", title: "Field notes: April", meta: "Edited yesterday" },
        { id: "d4", title: "Press kit", meta: "Edited 3d ago" },
      ],
    },
    {
      id: "info-activity",
      kind: "info",
      title: "Recent activity",
      icon: Activity,
      size: "xl",
      items: [
        { id: "a1", title: "Marco D. published “Brass lamp”", meta: "8m ago" },
        { id: "a2", title: "Sarah K. moderated 3 comments", meta: "32m ago" },
        { id: "a3", title: "Plugin update: Yoast SEO 22.4", meta: "1h ago" },
        { id: "a4", title: "Anya P. updated the homepage", meta: "2h ago" },
      ],
    },
    {
      id: "info-moderation",
      kind: "info",
      title: "Awaiting moderation",
      icon: MessageSquare,
      size: "xl",
      items: [
        { id: "m1", title: "Lee H. on “Linen tote”", meta: "“Is this restocked?”" },
        { id: "m2", title: "Anonymous on “Brass lamp”", meta: "Held — possible spam" },
        { id: "m3", title: "Priya R. on “Ceramic mug”", meta: "“Love the colour.”" },
      ],
    },
    {
      id: "nav-classic",
      kind: "nav",
      size: "tall",
      items: [
        {
          id: "n-posts",
          title: "Posts",
          icon: PenSquare,
          action: { type: "edit-page", params: { id: "posts" }, title: "Posts" },
        },
        {
          id: "n-pages",
          title: "Pages",
          icon: FileText,
          action: { type: "pages" },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-media",
          title: "Media",
          icon: Image,
          action: { type: "edit-page", params: { id: "media" }, title: "Media" },
        },
        {
          id: "n-comments",
          title: "Comments",
          icon: MessageSquare,
          action: { type: "edit-page", params: { id: "comments" }, title: "Comments" },
          badge: "3",
        },
        {
          id: "n-products",
          title: "Products",
          icon: Package,
          action: {
            type: "edit-page",
            params: { id: "products" },
            title: "Products",
          },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-orders",
          title: "Orders",
          icon: ShoppingBag,
          action: { type: "orders" },
          badge: "12",
          defaultPlacement: "dashboard",
        },
        {
          id: "n-product-reviews",
          title: "Product reviews",
          icon: Star,
          action: { type: "product-reviews" },
          badge: "8",
        },
        {
          id: "n-marketing",
          title: "Marketing",
          icon: Megaphone,
          action: { type: "marketing" },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-analytics",
          title: "Analytics",
          icon: BarChart3,
          action: { type: "analytics" },
          defaultPlacement: "dashboard",
        },
        {
          id: "n-users",
          title: "Users",
          icon: Users,
          action: { type: "edit-page", params: { id: "users" }, title: "Users" },
        },
        {
          id: "n-appearance",
          title: "Appearance",
          icon: Palette,
          action: { type: "editor", title: "Appearance" },
        },
        {
          id: "n-plugins",
          title: "Plugins",
          icon: Plug,
          action: { type: "edit-page", params: { id: "plugins" }, title: "Plugins" },
          badge: "2",
        },
        {
          id: "n-tools",
          title: "Tools",
          icon: Wrench,
          action: { type: "edit-page", params: { id: "tools" }, title: "Tools" },
        },
        {
          id: "n-settings",
          title: "Settings",
          icon: Settings,
          action: { type: "settings" },
        },
      ],
    },
  ],
}
