import {
  DollarSign,
  FileEdit,
  PackagePlus,
  Settings,
  ShoppingBag,
  Star,
  Tag,
  TrendingUp,
} from "lucide-react"
import type { Recipe } from "@/widgets/types"

export const storeManagerRecipe: Recipe = {
  id: "store-manager",
  role: "Store Manager",
  greeting: "Here’s what’s happening in your store today.",
  widgets: [
    {
      id: "tile-add-product",
      kind: "launch",
      title: "Add product",
      description: "Create a new listing",
      icon: PackagePlus,
      size: "sm",
      action: { type: "add-product" },
    },
    {
      id: "tile-orders",
      kind: "launch",
      title: "View orders",
      description: "12 awaiting fulfillment",
      icon: ShoppingBag,
      size: "sm",
      action: { type: "edit-page", params: { id: "orders" }, title: "Orders" },
    },
    {
      id: "tile-pricing",
      kind: "launch",
      title: "Update pricing",
      description: "Adjust catalog pricing",
      icon: Tag,
      size: "sm",
      action: { type: "edit-page", params: { id: "pricing" }, title: "Pricing" },
    },
    {
      id: "tile-settings",
      kind: "launch",
      title: "Store settings",
      description: "Tax, shipping, payments",
      icon: Settings,
      size: "sm",
      action: { type: "settings" },
    },
    {
      id: "metric-revenue",
      kind: "analytics",
      title: "Revenue this week",
      icon: DollarSign,
      size: "md",
      metric: {
        value: "$8,420",
        delta: { value: "+12.4%", trend: "up" },
        sparkline: [12, 14, 13, 18, 17, 22, 26],
        caption: "vs. last week",
      },
    },
    {
      id: "metric-orders",
      kind: "analytics",
      title: "Orders this week",
      icon: ShoppingBag,
      size: "md",
      metric: {
        value: "184",
        delta: { value: "+8", trend: "up" },
        sparkline: [22, 19, 24, 27, 31, 28, 33],
        caption: "vs. last week",
      },
    },
    {
      id: "metric-conversion",
      kind: "analytics",
      title: "Conversion rate",
      icon: TrendingUp,
      size: "md",
      metric: {
        value: "2.4%",
        delta: { value: "-0.2%", trend: "down" },
        sparkline: [2.7, 2.8, 2.6, 2.5, 2.4, 2.5, 2.4],
        caption: "vs. last week",
      },
    },
    {
      id: "info-recent-orders",
      kind: "info",
      title: "Recent orders",
      icon: ShoppingBag,
      size: "lg",
      items: [
        { id: "o1", title: "#1284 — Sarah K.", meta: "$129.00 · 2m ago" },
        { id: "o2", title: "#1283 — Marco D.", meta: "$48.00 · 38m ago" },
        { id: "o3", title: "#1282 — Anya P.", meta: "$210.00 · 1h ago" },
        { id: "o4", title: "#1281 — Lee H.", meta: "$76.00 · 2h ago" },
      ],
    },
    {
      id: "info-reviews",
      kind: "info",
      title: "New reviews",
      icon: Star,
      size: "lg",
      items: [
        { id: "r1", title: "★★★★★ Linen tote", meta: "“Beautiful quality.”" },
        { id: "r2", title: "★★★★☆ Brass lamp", meta: "“Sturdier than I expected.”" },
        { id: "r3", title: "★★★★★ Ceramic mug", meta: "“Bought four.”" },
      ],
    },
    {
      id: "nav-classic",
      kind: "nav",
      size: "lg",
      items: [
        {
          id: "n-pages",
          title: "Pages",
          icon: FileEdit,
          action: { type: "edit-page", params: { id: "home" }, title: "Pages" },
        },
        {
          id: "n-products",
          title: "Products",
          icon: PackagePlus,
          action: {
            type: "edit-page",
            params: { id: "products" },
            title: "Products",
          },
        },
        {
          id: "n-settings",
          title: "Settings",
          icon: Settings,
          action: { type: "settings" },
        },
      ],
    },
  ],
}
